# Site settings
title: Start Hacking
stylized: StartHacking.org
email: team@hackmit.org
description: >
  A guide to setting up a development environment on any platform for any
  project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://starthacking.org" # the base hostname & protocol for your site
content_source: "https://github.com/starthacking/starthacking.github.io/blob/develop/CONTRIBUTING.md#contributing"

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

# Settings
timezone: America/New_York
analytics:
  tracking_id: UA-53167467-5

# Excludes
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CONTRIBUTING.md
